### ISSUE TITLE
Runtime Error when judging C++

### ISSUE THREAD

**Issue by b0w1d** [peryaudo/tcjudge#4]
Is this repo still being maintained? It would really be helpful!
Here's the error message:
->
TopCoder Local Judge by peryaudo

tcjudge: login succeeded
Obtaining problem definition...ok.
Obtaining testcases...Traceback (most recent call last):
	7: from /Users/d0w0b/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `<main>'
	6: from /Users/d0w0b/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `eval'
	5: from /Users/d0w0b/.rvm/gems/ruby-2.5.0/bin/tcjudge:23:in `<main>'
	4: from /Users/d0w0b/.rvm/gems/ruby-2.5.0/bin/tcjudge:23:in `load'
	3: from /Users/d0w0b/.rvm/gems/ruby-2.5.0/gems/tcjudge-1.0.1/bin/tcjudge:9:in `<top (required)>'
	2: from /Users/d0w0b/.rvm/gems/ruby-2.5.0/gems/tcjudge-1.0.1/lib/tcjudge.rb:1459:in `start'
	1: from /Users/d0w0b/.rvm/gems/ruby-2.5.0/gems/tcjudge-1.0.1/lib/tcjudge.rb:1575:in `judge'
/Users/d0w0b/.rvm/gems/ruby-2.5.0/gems/tcjudge-1.0.1/lib/tcjudge.rb:131:in `get_test_cases': undefined method `xpath' for nil:NilClass (NoMethodError)

**Comment by peryaudo** [comment]
This repo is broken since the TopCoder website redesign, though I'd really appreciate if you could fix this.
I personally don't have any cycle to take a look at this right now, sorry about that.

**Comment by b0w1d** [comment]
I understand that. It's working somehow after executing it without the gem, you saved my day. I'm not an advanced Rubyist but making this better could be an interesting task for me to work on. BTW the diversity of topics and languages of your repo astonishes me! Thank you.
